### ISSUE TITLE
Problems with the stacking of several files

### ISSUE THREAD

**Issue by Martinez-Gregorio-Hector** [Martinez-Gregorio-Hector/workflow_to_analysis_WES#11]

**Comment by Martinez-Gregorio-Hector** [comment]
Hi 

I need to stack several files in only file, each file contains 46 columns and n row depending of the variants detected, This is the command that i used for this purpose 

```
#!/bin/bash

awk '{OFS="\t";print "TNBC_033", $0}' TNBC_033.txt  > merged.txt  \
awk '{OFS="\t";print "TNBC_034", $0}' TNBC_034.txt | sed 1d -  >> merged.txt \
awk '{OFS="\t";print "TNBC_035", $0}' TNBC_035.txt | sed 1d -  >> merged.txt 
```
when:
'{OFS="\t";print "TNBC_033", $0}' - Add one column in the beginning and fil with TNBC_033

I saved this command in (merged.sh)[https://github.com/Martinez-Gregorio-Hector/workflow_to_analysis_WES/blob/master/bin/merged.sh] and run **awk merged.sh** 
When I run this command only appeared the first file with the column added but didn't appear other files.

Someone advice

**Comment by Martinez-Gregorio-Hector** [comment]
To download files in the web using tydiverse

https://ohi-science.org/data-science-training/dplyr.html

**Comment by cristoichkov** [comment]
Hi everybody !!! 
I made a script in R, test it and tell me if it works fine.
```
## List the files
files <- list.files(".")

## Create a dataframe empty
df_hec <- data.frame()


for (i in files){
  
  ## Find the file name pattern
  name <- stringr::str_extract(string = i, pattern = "TNBC_[0-9]+")
  
##  Read the file
  red_hec <- read.table(i, sep = "\t", header = TRUE)
  
  ## Create a dataframe repeating the identifier according to with the number of row of the table 
  name_file <- data.frame(rep(name, times = nrow(red_hec)))
  
  ## Change the name of identifier column
  colnames(name_file) <- "Id"
  
  ## combine the data frames by columns
  final <- cbind(name_file, red_hec)
  
  ## combine the data frames by rows    
  df_hec <- rbind(df_hec, final)
}
```

**Comment by almamelisa** [comment]
``
tb33<-read_csv("Bioinformatica/TNBC_033.csv")
tb34<-read_csv('Bioinformatica/TNBC_034.csv')
tb35<-read_csv('Bioinformatica/TNBC_035.csv')

tb33f<-rep("TNBC_033", 873)
tb34f<-rep("TNBC_034", 218)
tb35f<-rep("TNBC_035", 157)

tb33<-cbind(tb33f,tb33)
tb33<-tb33[,-2]

tb34<-cbind(tb34f,tb34)
tb34<-tb34[,-2]

tb35<-cbind(tb35f,tb35)
tb35<-tb35[,-2]

tb33<-data.frame(tb33)
tb34<-data.frame(tb34)
tb35<-data.frame(tb35)

colnames(tb33)[1]<-"sample"
colnames(tb34)[1]<-"sample"
colnames(tb35)[1]<-"sample"

tbtodo<-rbind(tb33, tb34, tb35)
write_csv(tbtodo, file ="todo.csv")
```

**Comment by Melcatus** [comment]
in bash, but...missing the first column 

cat TNBC_033.txt > merge.txt
for i in TNBC_034.txt TNBC_035.txt; 
do sed -e '1d' $i >> merge.txt;
done

**Comment by camillethuyentruong** [comment]
Hi Hector,

With the following code R verifies that the rows or columns or the two tables are in the same order. It is useful to do it as a control before merging them

```
table1<-table2[rownames(table1),]
table1<-table2[colnames(table1),]
```

**Comment by Martinez-Gregorio-Hector** [comment]
thanks, this issue is closed

**Comment by cristoichkov** [comment]
Hi Hector
I know that you closed your repo, but I found the answer in bash.

```
#!/bin/bash

echo Id `awk '{if(NR==1) print $0}' TNBC_033.txt` | sed "s/ /\t/g" > merged.txt

awk '{if(NR!=1) print $0}' TNBC_033.txt | awk '{OFS="\t";print "TNBC_033", $0}' >> merged.txt

awk '{if(NR!=1) print $0}' TNBC_034.txt | awk '{OFS="\t";print "TNBC_034", $0}' >> merged.txt

awk '{if(NR!=1) print $0}' TNBC_035.txt | awk '{OFS="\t";print "TNBC_035", $0}' >> merged.txt

```

**Comment by Martinez-Gregorio-Hector** [comment]
Hi 
thanks for the information it's good to have both script.
Best,
MAGH
