### ISSUE TITLE
figure directory needs to be plural (figures)

### ISSUE THREAD

**Issue by AliciaMstt** [Martinez-Gregorio-Hector/workflow_to_analysis_WES#21]
This is a small English correction, but nonetheless needed:

your directory `figure` (singular) should be changed to `figures`.

When you do this, be careful to also update your README and scripts where `figures` is mentioned.

**Comment by Martinez-Gregorio-Hector** [comment]
Hi Alicia

Thanks for your advice, I have corrected the directory and where this word is mentioned.
