### ISSUE TITLE
Loop for Mutational Signature

### ISSUE THREAD

**Issue by Martinez-Gregorio-Hector** [Martinez-Gregorio-Hector/workflow_to_analysis_WES#9]
** Hi, I´m trying to do a loop to analyze  all my samples **

Regularly, run my analysis one by one in the deconstructSigs package but it’s slow so I’m trying to do a loop for analyze all my samples.

I have a problem in the last step. Before the last step I used the function mut.to.sigs.input, the mutational data is converted to an n-row and 96-columns data frame where n is the number of samples present. 

```
sigs.input <- mut.to.sigs.input(mut.ref = AllPatients, 
                                sample.id = "Sample", 
                                chr = "Chr", 
                                pos = "Start", 
                                ref = "Ref", 
                                alt = "Alt")  
```

The output of this function it looks like [this](https://github.com/Martinez-Gregorio-Hector/workflow_to_analysis_WES/blob/master/data/MutationalSignature/AllPatientsMutSig.csv)

The last step uses this function

```
AllPatients = whichSignatures(tumor.ref = sigs.input, 
                    signatures.ref = signatures.cosmic, 
                    sample.id = "sample1 ... n", 
                    contexts.needed = TRUE,
                    tri.counts.method = 'exome')
```

the data frame has not colnames and rownames that complicated me to make a loop but i try out with this function and only changing sample.id it does it one by one

```
for (i in sigs.input){
AllPatients = whichSignatures(tumor.ref = sigs.input, 
                    signatures.ref = signatures.cosmic, 
                    sample.id = "TNBC037", 
                    contexts.needed = TRUE,
                    tri.counts.method = 'exome')  
}
```

I need to help :(

**Comment by FernandaDiaz12** [comment]
Hi, we need access to the data frame from where you want to extract the data to create the loop.

**Comment by Duhyadi** [comment]
Hi, I think the following can help, each row can be used as a variable to analyze  ` for(i in c(1:nrow(df))){
  sample_name<-as.character(df[i,2])
  
  print(paste("hacer algo con la muestra", sample_name)) `

**Comment by FernandaDiaz12** [comment]
Hi Hector, try this yo define your categories:
Samples-01 <- factor(paste0(AllPatients$name))
were "name" = The name of the column with the sample's names in the table "AllPatients"

**Comment by Martinez-Gregorio-Hector** [comment]
Hi everyone
First, I could define my categories with this function

`x<-unique(signature$Sample)`

Second, ran the loop when x is the category defined above

```
for(i in x){
    a= whichSignatures(tumor.ref = sigs.input, 
                              signatures.ref = signatures.cosmic, 
                              sample.id = i, 
                              contexts.needed = TRUE,
                              tri.counts.method = 'exome')
assign(i,a)
}
```
Third, after the loop bound the dataframe with the following funtion 

```
TNBC033 <- rbind(t(TNBC033[["weights"]]),TNBC033[["unknown"]])
TNBC034 <- rbind(t(TNBC034[["weights"]]),TNBC034[["unknown"]])
TNBC035 <- rbind(t(TNBC035[["weights"]]),TNBC035[["unknown"]])
TNBC037 <- rbind(t(TNBC037[["weights"]]),TNBC037[["unknown"]])
TNBC038 <- rbind(t(TNBC038[["weights"]]),TNBC038[["unknown"]])

BindSignature <-cbind(TNBC033,TNBC034,TNBC035, TNBC037, TNBC038)
```

Finally, I exported my results in table 

`write.table(BindSignature,"SIGNATURE.txt",row.names = T, col.names = T, sep = "\t")`

The script complete is [here](https://github.com/Martinez-Gregorio-Hector/workflow_to_analysis_WES/tree/master/bin)

**Comment by Martinez-Gregorio-Hector** [comment]
Hi, we simplify the loop

1. Save the loop with this function also the iterations **Bind_Signature<-c()**
2. The loop was established in this way. x: is the vector where are the samples, a: is where is saved the result of the function whichSignatures

 ```
for(i in x){
    sample=i
    a= whichSignatures(tumor.ref = sigs.input, 
                              signatures.ref = signatures.cosmic, 
                              sample.id = i, 
                              contexts.needed = TRUE,
                              tri.counts.method = 'exome')
assign(i,a) # assign the name of the vector to the value obtained
```
3. The result of this loop is a list, we save the weight (signatures) and unknown (signature not detected) with the function below. This function does it for all samples

results<-cbind(sample, a$weights, a$unknown)  

4. After, we bind all sample with the function below. This create a matrix when the columns represents the signature and rows the samples.

Bind_Signature<-rbind(Bind_Signature, results)

The complete loop is 

```
Bind_Signature<-c()
for(i in x){
    sample=i
    a= whichSignatures(tumor.ref = sigs.input, 
                              signatures.ref = signatures.cosmic, 
                              sample.id = i, 
                              contexts.needed = TRUE,
                              tri.counts.method = 'exome')
assign(i,a) # assign the name of the vector to the value obtained
    
    
results<-cbind(sample, a$weights, a$unknown)  
    
Bind_Signature<-rbind(Bind_Signature, results)
row.names(Bind_Signature)<-NULL

}
colnames(Bind_Signature)[32]<-"unknown"
Bind_Signature
```

**Comment by Martinez-Gregorio-Hector** [comment]
And don't forget to add how to change it from wide to long format, and why this step was needed.
